const data = [
  {
    companyName: "에이아이에스",
    period: "2021-12 ~ 2023-12",
    occupation: "백엔드 개발자",
    link: "ais",
    rank: "주임",
    description: [
      "스마트팜 스타트업인 에이아이에스에서 주로 서버 관리 및 API 개발, 비즈니스 로직 업무를 수행하였습니다.",
    ],
    workExperience: [
      "개발팀의 일원으로 참여하여, 주로 서버 관리 및 API 개발, 비즈니스 로직 업무를 수행하였습니다.",
      "작물별 의사결정 알고리즘의 정확도를 향상시키기 위해 Linux 환경에서 프로그램을 실행하고 데이터의 유지보수를 담당했습니다. 또한, Zapier를 활용하여 Gitlab에서 이슈가 생성될 때 Slack 메시지가 전송되는 자동화 시스템을 구축하여 일종의 개발 알림 시스템처럼 사용하도록 하였습니다.",
      "문자 인증 API의 구현에서는 해당 기능의 특성을 고려하여 일시적으로 생성되고, 인증 만료 시간 동안만 유지되어야 하는 요구사항을 충족하기 위해 NoSQL인 Redis를 도입하여 구현하였습니다.",
      "NodeJS 기반의 환경에서의 개발 경험을 바탕으로 Express와 NestJS 프레임워크를 사용하여 프로젝트를 구축하였습니다. Sequelize와 TypeORM을 통한 ORM 라이브러리 사용 및 오픈 API 및 외부 API를 통한 데이터 정제 경험을 보유하고 있습니다.",
      "GitLab의 CI/CD를 활용하여 배치 서비스를 구현하고, JWT와 Redis를 이용하여 AT와 RT를 관리하여 로그인 기능을 구현하였습니다. 이 과정에서 FCM 토큰이 변경될 때의 비동기 로직 지연 현상을 최소화하기 위해 동기 로직으로 변경하여 프로세스의 효율성을 향상시키고 응답 시간을 최적화하였습니다.",
      "도커 컨테이너 환경에서 Next.js 프로젝트를 배포하고, Jest 라이브러리를 활용하여 E2E 테스트를 진행한 경험이 있습니다. 또한, 작물별 의사결정 알고리즘 로직 업무 프로세스를 도면으로 변경하여 보다 명확하고 수정 및 추가가 용이한 확장성 있는 구조로 개선한 경험이 있습니다.",
    ],
    history: [
      {
        workPeriod: "2022.01 ~ 2022.02",
        title: "문자 인증 기능 개발",
        people: "2명",
        member: "Backend 2명",
        skills: ["Express", "Redis"],
        description: "사내 앱/웹에서 사용되는 문자 인증 기능",
        jobDescription: ["프로젝트 아키텍처 설계", "Redis 세션 관리"],
      },
      {
        workPeriod: "2022.02 ~ 2022.06",
        title: "잘키움 앱 백엔드 개발",
        people: "6명",
        member: "Backend 3명, Frontend 2명, Designer 1명",
        skills: ["Express", "Sequelize", "MariaDB", "Gitlab CI/CD"],
        description:
          "작물 알고리즘을 기반으로 작물 환경 데이터를 수집 및 분석하여 작물을 1:1 맞춤으로 재배 관리하는 서비스",
        jobDescription: [
          "기상청, 웨더아이, 분 단위 기상대 오픈소스 및 외부 API 사용",
          "날씨, 농업, 알림 관련 조회, 생성, 수정, 삭제 기능 API 구현",
          "작물별 관수, 시비 의사결정 비즈니스 로직 구현",
          "서버 내 텍스트 파일 생성 및 수정 로직 구현",
          "Gitlab CI/CD로 의사결정 기능 자동화 처리",
        ],
      },
      {
        workPeriod: "2022.07 ~ 2022.08",
        title: "안동 미래과원 노지 스마트팜 잘키움 b2g 커스터마이징",
        people: "3명",
        member: "Backend 3명",
        skills: ["Express", "Sequelize", "MariaDB", "Goldilocks", "Jenkins"],
        description:
          "잘키움 서비스에 과수 모델을 추가하여 의사결정 비즈니스 로직 커스터마이징",
        jobDescription: [
          "무인장비 제어 비즈니스 로직 구현",
          "과수 관수, 시비 비즈니스 로직 구현",
          "Goldilocks odbc 적용",
          "Jenkins로 무인장비 및 비즈니스 로직 자동화 처리",
        ],
      },
      {
        workPeriod: "2022.08 ~ 2022.11",
        title: "잘키움 고도화",
        people: "3명",
        member: "Backend 3명",
        skills: ["Express", "Sequelize", "MariaDB", "Gitlab CI/CD"],
        description: "작물 추가 및 리소스 낭비 제어를 위한 기능 추가",
        jobDescription: [
          "탈퇴 및 미사용 서비스 제거 자동화 처리",
          "엑셀 파일 추출 로직 구현",
          "추가 작물 관수, 시비 비즈니스 로직 구현",
        ],
      },
      {
        workPeriod: "2022.12 ~ 2023.02",
        title: "관제 서비스",
        people: "2명",
        member: "Backend 2명",
        skills: ["Typescript", "Nest.js", "TypeORM", "Docker"],
        description: "잘키움의 데이터를 한 번에 볼 수 있는 관제 웹 서비스",
        jobDescription: [
          "프로젝트 아키텍처 설계 참여",
          "기상청, 웨더아이, 분 단위 기상대 오픈소스 및 외부 API 사용",
          "기업 회원 조회, 생성, 수정 기능 API 구현",
          "Jest E2E 테스트",
          "API 문서화를 위한 Swagger 도입",
          "Docker로 프로젝트 웹 배포",
        ],
      },
      {
        workPeriod: "2023.07 ~ 2023.11",
        title: "대행 앱 서비스 개발",
        people: "5명",
        member: "Team Leader 1명 Backend 2명 Frontend 2명",
        skills: ["Typescript", "Nest.js", "TypeORM", "Redis"],
        description: "잘키움의 데이터를 한 번에 볼 수 있는 관제 웹 서비스",
        jobDescription: [
          "프로젝트 아키텍처 설계 참여",
          "JWT, Redis, Guard를 활용한 AT, RT 관리 및 권한 부여 기능 구현",
          "토큰 재발급 API 구현",
          "농작업, 작업재, 유저 조회, 수정 기능 API 구현",
          "API 문서화를 위한 Swagger 도입",
        ],
      },
      {
        workPeriod: "2021.12 ~ 2023.12",
        title: "그 외 작업",
        people: "1명",
        member: "Backend 1명",
        skills: ["Zapier", "Slack", "MariaDB", "Linux"],
        description: "직접적인 개발 외 기여",
        jobDescription: [
          "Linux 환경에서 프로그램 실행 및 데이터 유지보수",
          "데이터베이스 테이블 설계",
          "업무 자동화 툴을 활용한 이슈 관리 도입",
          "Jira로 스프린트 계획 및 프로젝트 관리",
        ],
      },
    ],
  },
];

export default data;
